version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_server
    ports:
      - "3005:3005"
    env_file:
      - ./apps/server/.env
    depends_on:
      - redis
    networks:
      - app-network
      - monitor-net
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules 

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
      - monitor-net
    command: redis-server --appendonly yes

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitor-net
    depends_on:
      - prometheus

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
  monitor-net:
    driver: bridge