version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_server
    ports:
      - "3005:3005"
    env_file:
      - ./apps/server/.env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge