global:
  scrape_interval: 60s

remote_write:
  - url: ${GRAFANA_CLOUD_URL}
    basic_auth:
      username: ${GRAFANA_CLOUD_USER}
      password: ${GRAFANA_CLOUD_API_KEY}

scrape_configs:
  - job_name: nodejs_app
    static_configs:
      - targets: ["server:3005"]